package org.bouncycastle.jcajce.provider.kdf.hkdf;

import java.security.InvalidAlgorithmParameterException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.AlgorithmParameterSpec;
import java.util.ArrayList;
import java.util.List;

import javax.crypto.KDFParameters;
import javax.crypto.KDFSpi;
import javax.crypto.SecretKey;
import javax.crypto.spec.HKDFParameterSpec;
import javax.crypto.spec.SecretKeySpec;

import org.bouncycastle.crypto.Digest;
import org.bouncycastle.crypto.digests.SHA256Digest;
import org.bouncycastle.crypto.digests.SHA384Digest;
import org.bouncycastle.crypto.digests.SHA512Digest;
import org.bouncycastle.crypto.generators.HKDFBytesGenerator;
import org.bouncycastle.crypto.params.HKDFParameters;
import org.bouncycastle.util.Arrays;

public class HKDFSpi extends KDFSpi
{
    private final HKDFBytesGenerator hkdf;

    HKDFSpi(KDFParameters kdfParameters, Digest digest)
            throws InvalidAlgorithmParameterException
    {
        super(requireNull(kdfParameters, "HKDF" + " does not support parameters"));
        this.hkdf = new HKDFBytesGenerator(digest);
    }

    /**
     * Returns the {@code KDFParameters} used with this {@code KDF} object.
     * <p>
     * The returned parameters may be the same that were used to initialize
     * this {@code KDF} object, or may contain additional default or
     * random parameter values used by the underlying KDF algorithm.
     * If the required parameters were not supplied and can be generated by
     * the {@code KDF} object, the generated parameters are returned;
     * otherwise {@code null} is returned.
     *
     * @return the parameters used with this {@code KDF} object, or
     * {@code null}
     */
    @Override
    protected KDFParameters engineGetParameters()
    {
        return null;
    }

    @Override
    protected SecretKey engineDeriveKey(String alg, AlgorithmParameterSpec derivationSpec)
            throws InvalidAlgorithmParameterException, NoSuchAlgorithmException
    {
        byte[] derivedKey = engineDeriveData(derivationSpec);

        try
        {
            return new SecretKeySpec(derivedKey, alg);
        }
        finally
        {
            Arrays.clear(derivedKey);
        }
    }

    @Override
    protected byte[] engineDeriveData(AlgorithmParameterSpec derivationSpec)
            throws InvalidAlgorithmParameterException
    {
        if (derivationSpec instanceof org.bouncycastle.jcajce.spec.HKDFParameterSpec)
        {
            org.bouncycastle.jcajce.spec.HKDFParameterSpec spec = (org.bouncycastle.jcajce.spec.HKDFParameterSpec)derivationSpec;

            byte[] ikm = spec.getIKM();
            byte[] salt = spec.getSalt();
            byte[] info = spec.getInfo();

            return expand(spec.getOutputLength(), new HKDFParameters(ikm, salt, info));
        }

        if (!(derivationSpec instanceof HKDFParameterSpec))
        {
            throw new InvalidAlgorithmParameterException("Invalid AlgorithmParameterSpec provided");
        }

        if (derivationSpec instanceof HKDFParameterSpec.Expand)
        {
            HKDFParameterSpec.Expand spec = (HKDFParameterSpec.Expand)derivationSpec;

            byte[] ikm = spec.prk().getEncoded();
            byte[] info = spec.info();

            return expand(spec.length(), HKDFParameters.skipExtractParameters(ikm, info));
        }
        else if (derivationSpec instanceof HKDFParameterSpec.Extract)
        {
            HKDFParameterSpec.Extract spec = (HKDFParameterSpec.Extract)derivationSpec;

            byte[] ikm = flattenSecretKeys(spec.ikms());
            byte[] salt = flattenSecretKeys(spec.salts());

            return hkdf.extractPRK(salt, ikm);
        }
        else if (derivationSpec instanceof HKDFParameterSpec.ExtractThenExpand)
        {
            HKDFParameterSpec.ExtractThenExpand spec = (HKDFParameterSpec.ExtractThenExpand)derivationSpec;

            byte[] ikm = flattenSecretKeys(spec.ikms());
            byte[] salt = flattenSecretKeys(spec.salts());
            byte[] info = spec.info();

            return expand(spec.length(), new HKDFParameters(ikm, salt, info));
        }
        else if (derivationSpec instanceof org.bouncycastle.jcajce.spec.HKDFParameterSpec)
        {
            org.bouncycastle.jcajce.spec.HKDFParameterSpec spec = (org.bouncycastle.jcajce.spec.HKDFParameterSpec)derivationSpec;

            byte[] ikm = spec.getIKM();
            byte[] salt = spec.getSalt();
            byte[] info = spec.getInfo();

            return expand(spec.getOutputLength(), new HKDFParameters(ikm, salt, info));
        }
        else
        {
            throw new InvalidAlgorithmParameterException("invalid HKDFParameterSpec provided");
        }
    }

    private byte[] expand(int length, HKDFParameters hkdfParameters)
    {
        hkdf.init(hkdfParameters);

        byte[] result = new byte[length];
        hkdf.generateBytes(result, 0, length);
        return result;
    }

    private static byte[] flattenSecretKeys(List<SecretKey> keys)
    {
        if (keys.size() == 1)
        {
            return keys.get(0).getEncoded();
        }

        int len = 0;
        int off = 0;

        ArrayList<byte[]> encodings = new ArrayList<byte[]>(keys.size());
        for (SecretKey key : keys)
        {
            byte[] encoding = key.getEncoded(); 
            encodings.add(encoding);
            len += encoding.length;
        }

        byte[] res = new byte[len];
        for (byte[] encoding : encodings)
        {
            System.arraycopy(encoding, 0, res, off, encoding.length);
            off += encoding.length;
            Arrays.clear(encoding);
        }
        return res;
    }

    private static KDFParameters requireNull(KDFParameters kdfParameters, String message)
        throws InvalidAlgorithmParameterException
    {
        if (kdfParameters != null)
        {
            throw new InvalidAlgorithmParameterException(message);
        }
        return null;
    }

    public static class HKDFwithSHA256 extends HKDFSpi
    {
        public HKDFwithSHA256(KDFParameters kdfParameters) throws InvalidAlgorithmParameterException
        {
            super(kdfParameters, new SHA256Digest());
        }
        public HKDFwithSHA256() throws InvalidAlgorithmParameterException
        {
            this(null);
        }
    }

    public static class HKDFwithSHA384 extends HKDFSpi
    {
        public HKDFwithSHA384(KDFParameters kdfParameters) throws InvalidAlgorithmParameterException
        {
            super(kdfParameters, new SHA384Digest());
        }
        public HKDFwithSHA384() throws InvalidAlgorithmParameterException
        {
            this(null);
        }
    }

    public static class HKDFwithSHA512 extends HKDFSpi
    {
        public HKDFwithSHA512(KDFParameters kdfParameters) throws InvalidAlgorithmParameterException
        {
            super(kdfParameters, new SHA512Digest());
        }
        public HKDFwithSHA512() throws InvalidAlgorithmParameterException
        {
            this(null);
        }
    }
}
