#!/bin/sh -
#
# build script for 1.3
#
# If it's given a buildname it creates a subdirectory and places a build in it,
# otherwise it just creates the docs and class files.
#

JDKPATH=/opt/jdk1.3.1  # JDK 1.3 location
XALAN_HOME=../apache/xalan-j_2_7_0
W3C_HOME=../w3c

JAVA_HOME=$JDKPATH
export JAVA_HOME

PATH=$JDKPATH/bin:$PATH
export PATH

CLASSPATH=$JAVA_MAIL_HOME/mail.jar:$JAVA_ACTIVATION_HOME/activation.jar:$W3C_HOME/w3c.jar:$XALAN_HOME/serializer.jar:$XALAN_HOME/xalan.jar:$XALAN_HOME/xercesImpl.jar:$XALAN_HOME/xml-apis.jar:$XALAN_HOME/xsltc.jar:$CLASSPATH
export CLASSPATH

if [ "$1" = "test" ]
then
    ant -f ant/jdk13.xml test
else
if [ "$1" = "provider" ]
then
    ant -f ant/jdk13.xml build-provider
    ant -f ant/jdk13.xml zip-src-provider
else
    if ant -f ant/jdk13.xml build-jce
    then
        ant -f ant/jdk13.xml build
        ant -f ant/jdk13.xml zip-src
    fi
fi
fi
