#!/bin/sh -
#
# build script for 1.5
#
# If it's given a buildname it creates a subdirectory and places a build in it,
# otherwise it just creates the docs and class files.
#

if [ "${JDKPATH}" = "" ] 
then
	JDKPATH=/opt/jdk1.5.0   # JDK 1.5 location
	JAVA_MAIL_HOME=/opt/javamail
	JAVA_ACTIVATION_HOME=/opt/jaf
	JUNIT_HOME=/opt/junit
fi

JAVA_HOME=$JDKPATH
export JAVA_HOME

PATH=$JDKPATH/bin:$PATH
export PATH

CLASSPATH=$JAVA_MAIL_HOME/mail.jar:$JAVA_ACTIVATION_HOME/activation.jar:$JUNIT_HOME/junit.jar:$CLASSPATH
export CLASSPATH

if [ "$1" = "test" ]
then
    ant -f ant/jdk15+.xml test
else
    if ant -f ant/jdk15+.xml build-provider
    then
        ant -f ant/jdk15+.xml build
        ant -f ant/jdk15+.xml zip-src
    fi
fi

