#!/bin/sh -
#
# build script for 1.5
#
# If it's given a buildname it creates a subdirectory and places a build in it,
# otherwise it just creates the docs and class files.
#

if [ "${JDKPATH}" = "" ] 
then
	JDKPATH=/usr/lib/jvm/java-7-openjdk-amd64
fi

JAVA_HOME=$JDKPATH
export JAVA_HOME

PATH=$JDKPATH/bin:$PATH
export PATH

if [ "$1" = "test" ]
then
    ant -f ant/jdk15+.xml test
else
    if ant -f ant/jdk15+.xml build-provider
    then
        ant -f ant/jdk15+.xml build
        ant -f ant/jdk15+.xml zip-src
    fi
fi

