package org.bouncycastle.crypto.params;

import javax.security.auth.Destroyable;

import org.bouncycastle.math.ec.ECPoint;
import org.bouncycastle.math.ec.sm9.SM9Curve;

/**
 * A user's SM9 signature private key ds_A = [t2]P1, a point of G1
 * (GM/T 0044.2-2016). Generated by the KGC from the signature master private
 * key and the user's identity. Carries a reference to the master public key,
 * which the signer needs to compute g = e(P1, P_pub-s).
 */
public class SM9SignPrivateKeyParameters
    extends AsymmetricKeyParameter
    implements Destroyable
{
    private ECPoint ds;
    private volatile boolean destroyed;
    private final SM9SignMasterPublicKeyParameters masterPublicKey;

    SM9SignPrivateKeyParameters(ECPoint ds, SM9SignMasterPublicKeyParameters masterPublicKey)
    {
        super(true);
        this.ds = ds;
        this.masterPublicKey = masterPublicKey;
    }

    public ECPoint getPrivatePoint()
    {
        return checkedDs();
    }

    public SM9SignMasterPublicKeyParameters getMasterPublicKey()
    {
        return masterPublicKey;
    }

    /**
     * The user's signature private key point ds of G1 in uncompressed form
     * (0x04 || x || y, 65 bytes). The master public key is not part of this
     * encoding; supply it via {@link #fromEncoded} to rebuild a usable key.
     */
    public byte[] getEncoded()
    {
        return checkedDs().getEncoded(false);
    }

    public static SM9SignPrivateKeyParameters fromEncoded(byte[] enc, SM9SignMasterPublicKeyParameters masterPublicKey)
    {
        return new SM9SignPrivateKeyParameters(SM9Curve.G1.decodePoint(enc), masterPublicKey);
    }

    /**
     * Destroy this object, dropping its reference to the private point ds.
     * <p>
     * As the point's coordinates are immutable they cannot be zeroized in place;
     * destruction drops the reference and marks the key destroyed, after which
     * {@link #getPrivatePoint()} and {@link #getEncoded()} throw
     * {@link IllegalStateException}. The master public key remains available.
     */
    public synchronized void destroy()
    {
        if (!destroyed)
        {
            destroyed = true;
            ds = null;
        }
    }

    public boolean isDestroyed()
    {
        return destroyed;
    }

    private ECPoint checkedDs()
    {
        // the null check catches a destroy() in progress whose flag write is not yet visible;
        // as the point is immutable a non-null snapshot is always the intact pre-destroy value.
        ECPoint value = this.ds;
        if (destroyed || value == null)
        {
            throw new IllegalStateException("key destroyed");
        }
        return value;
    }
}
