package org.bouncycastle.crypto.params;

import java.math.BigInteger;

import javax.security.auth.Destroyable;

import org.bouncycastle.crypto.CryptoServicesRegistrar;
import org.bouncycastle.crypto.generators.SM9Sm3;
import org.bouncycastle.math.ec.ECPoint;
import org.bouncycastle.math.ec.sm9.SM9Curve;
import org.bouncycastle.math.ec.sm9.SM9G2Point;
import org.bouncycastle.math.ec.sm9.SM9Pairing;
import org.bouncycastle.util.Arrays;
import org.bouncycastle.util.BigIntegers;

/**
 * A user's SM9 signature private key ds_A = [t2]P1, a point of G1
 * (GM/T 0044.2-2016). Generated by the KGC from the signature master private
 * key and the user's identity. Carries the identity (needed by nothing in this
 * class directly, but part of what a caller needs to identify the key) and a
 * reference to the master public key, which the signer needs to compute
 * g = e(P1, P_pub-s).
 */
public class SM9SigPrivateKeyParameters
    extends AsymmetricKeyParameter
    implements Destroyable
{
    private ECPoint ds;
    private volatile boolean destroyed;
    private final SM9SigMasterPublicKeyParameters masterPublicKey;
    private final byte[] identity;

    SM9SigPrivateKeyParameters(ECPoint ds, SM9SigMasterPublicKeyParameters masterPublicKey, byte[] identity)
    {
        super(true);
        this.ds = ds;
        this.masterPublicKey = masterPublicKey;
        this.identity = Arrays.clone(identity);
    }

    public ECPoint getPrivatePoint()
    {
        return checkedDs();
    }

    public SM9SigMasterPublicKeyParameters getMasterPublicKey()
    {
        return masterPublicKey;
    }

    /**
     * The identity this key was derived for. Synchronized with {@link #destroy()}, which zeroes
     * the array in place: the flag is set before the clear, but reading a byte the clear has
     * already written does not order the reader after the flag, so an unsynchronized copy could
     * return a partly zeroed identity with the flag still reading false.
     */
    public synchronized byte[] getIdentity()
    {
        if (destroyed)
        {
            throw new IllegalStateException("key destroyed");
        }
        return Arrays.clone(identity);
    }

    /**
     * The user's signature private key point ds of G1 in uncompressed form
     * (0x04 || x || y, 65 bytes). The master public key and identity are not
     * part of this encoding; supply them via {@link #fromEncoded} to rebuild
     * a usable key.
     */
    public byte[] getEncoded()
    {
        return checkedDs().getEncoded(false);
    }

    /**
     * Rebuild a signature user key from its bare point encoding, under the master public key
     * and identity it was derived for, which the encoding does not carry. The point is refused
     * unless it is a point of G1 other than the point at infinity.
     * <p>
     * The point is also checked against the master public key and identity, by the KGC's own
     * relation e(ds, [H1(ID || hid, N)]P2 + P_pub-s) = e(P1, P_pub-s), which holds exactly when
     * ds = [ks * (H1(ID || hid, N) + ks)^-1]P1 for the ks behind that P_pub-s: a point paired
     * with another master public key, or filed under another identity, is refused with an
     * {@link IllegalArgumentException} rather than imported as a key whose signatures would not
     * verify. ds is secret and the pairing takes its G1 argument to be public, so the relation
     * is checked on [r]ds for a random r, against e(P1, P_pub-s)^r, raised as signing raises it.
     * The check costs a pairing and about what a signature costs.
     *
     * @param enc the encoding {@link #getEncoded()} writes.
     * @param masterPublicKey the signature master public key the key was derived under.
     * @param identity the identity the key was derived for.
     * @return the rebuilt key.
     */
    public static SM9SigPrivateKeyParameters fromEncoded(
        byte[] enc, SM9SigMasterPublicKeyParameters masterPublicKey, byte[] identity)
    {
        checkContext(masterPublicKey, identity);
        ECPoint ds = SM9Curve.g1FromUncompressed(enc);
        if (ds.isInfinity())
        {
            // ds_A = [t2]P1 with t2 in [1, N-1] never is; signing with it would emit an S at
            // infinity, which encodes as the single octet 0x00 and which no verifier accepts
            throw new IllegalArgumentException("SM9 signature private key cannot be the point at infinity");
        }
        return checked(ds, masterPublicKey, identity);
    }

    // the key ds is, once it is checked to be the key the KGC derives for identity under masterPublicKey:
    // e([r]ds, [H1(ID || hid, N)]P2 + P_pub-s) = e(P1, P_pub-s)^r, for r drawn here so that the pairing,
    // which takes its G1 point to be public, works on a uniformly random point rather than on ds
    private static SM9SigPrivateKeyParameters checked(ECPoint ds, SM9SigMasterPublicKeyParameters masterPublicKey,
                                                      byte[] identity)
    {
        BigInteger n = SM9Curve.N;
        BigInteger h1 = SM9Sm3.h1(Arrays.append(identity, SM9SigMasterPrivateKeyParameters.HID), n);
        SM9G2Point q = SM9Curve.P2.multiply(h1).add(masterPublicKey.getPointG2());
        BigInteger r = BigIntegers.createRandomInRange(BigIntegers.ONE, n.subtract(BigIntegers.ONE),
            CryptoServicesRegistrar.getSecureRandom());
        // q at infinity is the identity no user key can be derived for under this master key
        if (q.isInfinity() || !SM9Pairing.pairing(SM9Curve.multiplySecure(ds, r), q).equals(
            masterPublicKey.pairingWithP1().powSecureFixedBase(r)))
        {
            throw new IllegalArgumentException(
                "SM9 signature private key does not match its master public key and identity");
        }
        return new SM9SigPrivateKeyParameters(ds, masterPublicKey, identity);
    }

    /**
     * The master public key and identity a rebuilt key is paired with. Neither may be absent:
     * a null master key produced an object that threw NullPointerException from the signer or
     * from a JCA wrapper's hashCode() much later, and an absent identity is the value most
     * likely to have come from a lookup that failed - it would silently key the holder as
     * whoever the empty identity is, rather than as no one.
     */
    static void checkContext(Object masterPublicKey, byte[] identity)
    {
        if (masterPublicKey == null)
        {
            throw new NullPointerException("masterPublicKey cannot be null");
        }
        if (identity == null)
        {
            throw new NullPointerException("identity cannot be null");
        }
        if (identity.length == 0)
        {
            throw new IllegalArgumentException("identity cannot be empty");
        }
    }

    /**
     * Destroy this object, dropping its reference to the private point ds and
     * zeroizing the identity.
     * <p>
     * As the point's coordinates are immutable they cannot be zeroized in place;
     * destruction drops the reference and marks the key destroyed, after which
     * {@link #getPrivatePoint()}, {@link #getEncoded()} and {@link #getIdentity()}
     * throw {@link IllegalStateException}. The master public key remains available.
     */
    public synchronized void destroy()
    {
        if (!destroyed)
        {
            destroyed = true;
            ds = null;
            Arrays.clear(identity);
        }
    }

    public boolean isDestroyed()
    {
        return destroyed;
    }

    private ECPoint checkedDs()
    {
        // the null check catches a destroy() in progress whose flag write is not yet visible;
        // as the point is immutable a non-null snapshot is always the intact pre-destroy value.
        ECPoint value = this.ds;
        if (destroyed || value == null)
        {
            throw new IllegalStateException("key destroyed");
        }
        return value;
    }
}
