package org.bouncycastle.crypto.params;

import javax.security.auth.Destroyable;

import org.bouncycastle.math.ec.ECPoint;
import org.bouncycastle.math.ec.sm9.SM9Curve;
import org.bouncycastle.util.Arrays;

/**
 * A user's SM9 signature private key ds_A = [t2]P1, a point of G1
 * (GM/T 0044.2-2016). Generated by the KGC from the signature master private
 * key and the user's identity. Carries the identity (needed by nothing in this
 * class directly, but part of what a caller needs to identify the key) and a
 * reference to the master public key, which the signer needs to compute
 * g = e(P1, P_pub-s).
 */
public class SM9SigPrivateKeyParameters
    extends AsymmetricKeyParameter
    implements Destroyable
{
    private ECPoint ds;
    private volatile boolean destroyed;
    private final SM9SigMasterPublicKeyParameters masterPublicKey;
    private final byte[] identity;

    SM9SigPrivateKeyParameters(ECPoint ds, SM9SigMasterPublicKeyParameters masterPublicKey, byte[] identity)
    {
        super(true);
        this.ds = ds;
        this.masterPublicKey = masterPublicKey;
        this.identity = Arrays.clone(identity);
    }

    public ECPoint getPrivatePoint()
    {
        return checkedDs();
    }

    public SM9SigMasterPublicKeyParameters getMasterPublicKey()
    {
        return masterPublicKey;
    }

    public byte[] getIdentity()
    {
        byte[] value = Arrays.clone(identity);
        if (destroyed)
        {
            throw new IllegalStateException("key destroyed");
        }
        return value;
    }

    /**
     * The user's signature private key point ds of G1 in uncompressed form
     * (0x04 || x || y, 65 bytes). The master public key and identity are not
     * part of this encoding; supply them via {@link #fromEncoded} to rebuild
     * a usable key.
     */
    public byte[] getEncoded()
    {
        return checkedDs().getEncoded(false);
    }

    public static SM9SigPrivateKeyParameters fromEncoded(
        byte[] enc, SM9SigMasterPublicKeyParameters masterPublicKey, byte[] identity)
    {
        return new SM9SigPrivateKeyParameters(SM9Curve.G1.decodePoint(enc), masterPublicKey, identity);
    }

    /**
     * Destroy this object, dropping its reference to the private point ds and
     * zeroizing the identity.
     * <p>
     * As the point's coordinates are immutable they cannot be zeroized in place;
     * destruction drops the reference and marks the key destroyed, after which
     * {@link #getPrivatePoint()}, {@link #getEncoded()} and {@link #getIdentity()}
     * throw {@link IllegalStateException}. The master public key remains available.
     */
    public synchronized void destroy()
    {
        if (!destroyed)
        {
            destroyed = true;
            ds = null;
            Arrays.clear(identity);
        }
    }

    public boolean isDestroyed()
    {
        return destroyed;
    }

    private ECPoint checkedDs()
    {
        // the null check catches a destroy() in progress whose flag write is not yet visible;
        // as the point is immutable a non-null snapshot is always the intact pre-destroy value.
        ECPoint value = this.ds;
        if (destroyed || value == null)
        {
            throw new IllegalStateException("key destroyed");
        }
        return value;
    }
}
