package org.bouncycastle.crypto.test;

import org.bouncycastle.crypto.modes.XChaCha20Poly1305;
import org.bouncycastle.crypto.params.AEADParameters;
import org.bouncycastle.crypto.params.KeyParameter;
import org.bouncycastle.crypto.params.ParametersWithIV;
import org.bouncycastle.util.Arrays;
import org.bouncycastle.util.encoders.Hex;
import org.bouncycastle.util.test.SimpleTest;

public class XChaCha20Poly1305Test extends SimpleTest
{

    private static class TestCase
    {

        private final byte[] key;
        private final byte[] iv;
        private final byte[] plaintext;
        private final byte[] aad;
        private final byte[] taggedCiphertext;

        public TestCase(String key, String iv, String plaintext, String aad,
            String taggedCiphertext)
        {
            this.key = Hex.decode(key);
            this.iv = Hex.decode(iv);
            this.plaintext = Hex.decode(plaintext);
            this.aad = Hex.decode(aad);
            this.taggedCiphertext = Hex.decode(taggedCiphertext);
        }

        public byte[] getKey()
        {
            return key;
        }

        public byte[] getIv()
        {
            return iv;
        }

        public byte[] getPlaintext()
        {
            return plaintext;
        }

        public byte[] getAad()
        {
            return aad;
        }

        public byte[] getTaggedCiphertext()
        {
            return taggedCiphertext;
        }
    }

    // Test cases randomly generated by libsodium
    private static final TestCase[] TEST_CASES = new TestCase[]{
        new TestCase("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f",
            "404142434445464748494a4b4c4d4e4f5051525354555657",
            "4c616469657320616e642047656e746c656d656e206f662074686520636c617373206f66202739393a204966204920636f756c64206f6666657220796f75206f6e6c79206f6e652074697020666f7220746865206675747572652c2073756e73637265656e20776f756c642062652069742e",
            "50515253c0c1c2c3c4c5c6c7",
            "bd6d179d3e83d43b9576579493c0e939572a1700252bfaccbed2902c21396cbb731c7f1b0b4aa6440bf3a82f4eda7e39ae64c6708c54c216cb96b72e1213b4522f8c9ba40db5d945b11b69b982c1bb9e3f3fac2bc369488f76b2383565d3fff921f9664c97637da9768812f615c68b13b52ec0875924c1c7987947deafd8780acf49"),
        new TestCase("091b328d56f9e584d771a7d94b541ffd365c1f421f708574eb958db12337555f",
            "aaf932005aea94e1ba42fdb878047254cfce60a36e6cac84",
            "388109916fce12994316221ae27ef74d3a0bcda727fedad6a8ea2192d16f624fdbbd051de74ac1db74",
            "0b7e9b1170fd59bd678e87f9404a1ca143ac1a9f1432e6d16fe789ff66bced6f7c3d351d270ea2a5892fa4f315f67bcfe1b7cb76b805",
            "46e9c8995c53d3a345230a830272bace62b16808fecc1e4ef7d75aeb7d05049aeb0be6db05f0f1da34e9b912a380430946def04001b5fe5ba1"),
        new TestCase("939419b46630b7438ff85f6e77b6b7451e2a3888f8631710f6259c700c7431ee",
            "98a1dfdda1745e6359b02c0afb69cb3b2688fbd57cdc9585",
            "7414f45787de1935d39c7529c195d5cba7a7b1cded510e32a3bcd2cfc6a1a4cfe89032eff7ee5437f9f277c5ad4583df271c6a8363",
            "d235b8a07532d5f127d707f4630bd2ce23bafb82eb8f07baa9e7e8b513b3f6edfeee1aed11132709",
            "dda44e5f0758746dc84d00c8e62128a2ed98baab377c888481e23a163f1cfcb604f627eb5d4c5f0041c8b86972ad3f6c1cacea6f159c784642a00738be24aecd98142b3131"),
        new TestCase("53862f0a4b8df9c19c0b58672f5a20c2516a86c24f0ec80062896db2bcffc784",
            "35cf7c63727c472a42b4295923e5dca7b1f00a1b5fd766d8",
            "5e62527ee8f16833fc11c243317b88f2d3323757ca394c4436df112192c96645c6388edeebb6c7a9d7966cd5fae64b8a49c2d754ffa02b6f9793f356f84459fbc8ef4bac7327eedf6bc602fb336dea",
            "dabb6b51c02278273dbb4baae238ec5f",
            "2c6671d3c176d864fc2ee72101b73bfb7d74f4ea948d0a61392634756fe4a25402ca96d70139cdebb5c90f5bedde3d406033ca15f8a37944dd2a9c51da8841e52116675df49acd3d89a1a00ec386270fd41fa03728be476aa74829b373f0f9"),
        new TestCase("88eb83d5290886e29df44b16133fe81d6086945ef77b487449ba97eede2ec96a",
            "040c9392d2806e60579348b025c3450f98f895fcd397a4b3",
            "881fc800cc55cf02699394db3de2440b47bee8208d9873b3dc1b5c5417b3a5998d649f16838cc5a1912fed46a7d20dc2a58dd1c69a7ad85d50ab485c8756473b94cc2439936a1d05e2acd69fbd19b915695bdd7f298821b1eb139e",
            "87",
            "19064dd3a9a26b01549d7e7be47f393d7b1d9cb1180726e788b096df7e30d8e940d1308a90849b98a8a02e6117a89c59681169b0c96cdeabda081b0ddcf20003f17f0bd9cb416a5c3d0ba6287c214854a63de6aa82c17a037e2aaf96a05fb55b64457be615260a04f65f43"),
        new TestCase("736353a6798e0fffaef2ceeb4e2cc12173156f8c9504c76ec0b4352ef0222003",
            "6d481374ff1d92f0bae325ff8166903052b61babd6f65567",
            "20a4eec9376e7bf3ed8f52152707bf0ef214794fb759df6416fcd42d5dc441abb6428d11399cca54c0e861b2684e0e24d3d81b9f4f396e697483218e6dcbdb8960543e504eb9682acf2200808ddc74462c325f8ebf11c125640060682e5f84b886f5660e1f026b588c964a492e94cf",
            "69",
            "5ec5f66b3e72ffc476f2c1a570ad76592baf1b341076720e65cde18859d40caaae388ff27bb735b9b83ff8a8a32892a556292fd11e3eaba606df5aff518e0a3885a3e89781d2a5c58e7d3246b5e4cbf48bd59a7559866bda69bc48a785d6dee8daa1d107e08f90b4168495e0d93a5dec8436bb36d3b90e8ce1720d80c06ff5"),
        new TestCase("b85acb3d38e58e3e0e5c18d0b3a90aa53cee466e17d0c997c5ffeea0324c5e13",
            "de33f235b18392ba2666eba717f4f774a8b8d186129a6b8e",
            "aee6c6db6578b7e48fa1a7f142441d95ddd0bf690223563e5917d097623ec1c518a6668101c2ca8a3f909adf0aaa78d72178694e7799f6a1d37543b56aabd3c445507e612b4aa6b1a390031101070264abeb09e486a4252836e464c1a26e",
            "cd9bb15dbf6fbc676731b011b5cc92874051682f38acdc8b91bf27b3793b25341556bf67d56e6f",
            "c52c2ca2652c9783503e60f9c3c3cf737a8dedf791675dd76fa85991ecfa42953b94c566affd264de6ef29a9cffa51a9a7dcd0469c307289baad3a78fd5192113b63efd93ad012ec6bb05b935ab34f0ebe994e06575665dc2f64c8e8f6ac209458ffdbc48e6915b28fe950c619fb"),
        new TestCase("2a9b873f6faf3992c05d531aaaae873353d4da31067f2497e3ab8fc337d4c0fd",
            "859beebf5d6aff8c37a9c850478731f33b455c0f168f852c",
            "13452a24bcc354428b0c31d9a58f7239cc344066be588b044207395a62cbaadd43f8689e9704fd80f7f2b47b9754676b2ee3a6e38f3f38d875efcf9366407649e4b3018bc68865e815ea74e42d4e",
            "ede91d919d6db87b2ba16cc301c01f3057919b82a704b873f5979fabc72c4b",
            "d82a9b49d0216048d1310aed0cb1225a0291e3368d01b1be5098b7974520a85841288246dc5a58d75b16f81ca201bc297e4705fea2360cc706b52db68356528390da7c3c677923d77061731fb92a52564df01a41ed93a8f02ea85d5be1c6"),
        new TestCase("17317a9b895fa885b302b895abc5e382943aaaa37b06a9e5dc1fcf7e8eb5392b",
            "0f86aeeea6d8e81e2cac7a6123f239458b8f6fe4d3f5ed36",
            "c7dd7f40ea288564b06b07e2db953256eb37131d7f6439e53e3115025fc5d4cb3da26b72c86d9e09ad78",
            "fb9cb095f4a2db",
            "20a849f5ca136773d55db982d7ae09c630d65dae6ce5924c01c96a8a6ba1e6c89d94cbdb7db0f9d9f5fd7ef488d8a2ae165a5411b6aa5b741580"),
        new TestCase("7239d52dde582ee478c2d9f4356862fc852cbb91f9f6f4c02e5deeff12e45da4",
            "94366355a5bac385d0ceff6ef4faa0ab163afc6d2bed91d5", "eb5c7cf0cb84a67a2bf3cbfd",
            "371a661b485bef33abe4387a2eb7f33b62795773d6c326da666f9634b6120fcab82a766c52f84961d40bb548e5fc610b7b8f0c0dea95",
            "c36bccc6823f7f688b245436d8943ef58a2ad2d877cf47a919420f88"),
        new TestCase("460a7e604d2cb558be74e95bd2ed3e835d46a77c4e531de32f1946f7d50841a2",
            "82b9f1c0838ee20c1816762c480e09e474ff87af9a015891",
            "460400404d2838ab8d1db3dfedb0fb538635860c189b1cfba0da467da12c3f6137d3e7146fb00c62a11bce45c8bcfca57edff18661ac5feedf8b",
            "8135e6cb133b3edaf94902f0c124",
            "9365bd370c047f8313aebf34e0bf3359f7dee954ce542cff3bb8c0c0e18122295a772cc7d7703bdd4433ba3839d46671d3338146db12c0f121d45ce2296c6b96800a2692deed16997f9d"),
        new TestCase("5793f3fc2dfe3539ba27528a1dbf483203e9c911c102b90118ef46e43797bbd8",
            "db5afb8672ab9041decb0e4fa70e91e7a77ad50f44f2f941",
            "9309c9855594e0019e8b052759539a7ba7297f984deba5422ec6da66c8d06647b92bcbadc15d8077c8d580373d9c9f3511a668711641c5d2e80161f533d9ccb3e21f691b37a9bb6b73016256d949e72a02a212b069827a502624288d7cfd",
            "a5a59b8186412b6f",
            "583a07049f8f7c53da94c290fd208f4168a04e8dbf750ff658e93c4eab3287df5e91f866df19312ca23d2c83e5768fdb25adec860e30ec0448e00fd090b29a2606d005e632a93e50418de9b98458ee0b62106bfaaca44b6ef88a0ab7b46bfe182c8249592815a17c324d5cadcd24"),
        new TestCase("ebb6fd81106ce21d1ab0a7f7a27151d928661361669f3046cefbeaa2aced3617",
            "9b881299dbb29c0117784f91cf04b710f3b578c02bd87346",
            "169cd1f3e17e3bf3bc5c5451abdd42be29b20760",
            "8277aa1b7784ae88432108b251730ac4dca4d1d90eb42e15ef368377826bc56d28d92dbc45912de607eaa7142bb899ae0f",
            "68bfc9aa111d12d2c05e2c9e0571b859f47ddba6cad0411334f4cdfcbc5fd6d4be64513d"),
        new TestCase("2c82b36af3c5a8124032890ec818a00a04c023570d51500e621b368b346b5eb6",
            "e4f6658c95318e4712103ec174be202388b5f1e65bd487d0", "d62a0037876e",
            "d1a19c0d6c333fbc15cb9457caf04583873531bd241b49e79865",
            "3e15f9336af6626206dd6464b60f247b0527296982d3"),
        new TestCase("800881c00c9d03330db3d6713a68638d1e0224742401125d351123549d4bdb52",
            "b20e77b4869022a5947c9d8ecbceb8b21d664ef1b33890bd",
            "f68e14b8461287245e8e89e35197316a8ac047e8e6932ba11c923bf530b6320d4c18bd53526a09cd98ce700ae3ce378fc5a6d77afadab93d64346da88fdeedd4942ea4b97beae782a1a3f671aef5634545c6a9b1b91908cb0346679cd1fc",
            "bad2ade2460f7a7be05e82225e3701",
            "8b814e5a5b92537fa7998852670588c47b15b3100f0742b1d06c20def5ae9555e4a59f02c10e985e34b41a2adbce6e9f0c1f02f62b7519147278d524151d1ab06cef5c6b6d6371bf939cfdd6c57b0e646ac95635790b03d875272ddcfa9c0cccaf46619c7f63d33abeefba33f03f"),
        new TestCase("e14cc36b2e4657128e462a73aea25a5b15d5ec8917faf415bc0580ac7cfd0e5f",
            "3c212f13e8d26f6719f3c5a6ea414330994582fd14e989ef",
            "650fa8359a5c2e83b6685e1db9d9124b85f7ecdba61935e6b5ed2fb8",
            "fd0df3d8aa5fc24265107e7621301f781fcebdd21c1c8d696bbe3d18055f5d66827a53e4e79ce0e5495a64668a8718b82d4d6ce78c5da20d",
            "09c88d4dc277ba69fb2b043a08dc73a8f248966aab2ebe889e0e222c31932de593821781481144bf4f47dcd1"),
        new TestCase("17e4febc9a229c3d98848090aa0f7d14fc654867b093de0555557168b16f1a51",
            "1cddef425b48d7f9cfe1798f7f035d74cd0f6831421a9e4d",
            "163c4dc339a3d29858f27bb5798f7020e4388fb17eadd64a65b7998ee37583adbd02e805264fdb0d4e17e343140656bc6a23ec8ccf0dbfddb7cf0f7221fe486a8c448eed5c7141",
            "05478f4551b2f5cd63ca6a712deb89a5e301e3937b7a6503038fbf970327930d",
            "82871babefc82d27f471a13b5b553aef343c89795c2083d6b3b675c9ecaf6d374d9f9e7707af40538fdedb2f7a5af116531672909f3e03da6df8377a1afa8bf499071972924b2426f08aa06273b41650886815329e246d"),
        new TestCase("d044beed1512d77ae932392a7d7b74784596ddd9a395c04bfa3e51e8ea3ddae8",
            "cbaef78c420218e4e1c98c136887438165f0b9631899bbaa",
            "f4eb98202bc6fb5b5372a4383e07352f46de5917b43b596941a18847b3cd03eda19092df247c46b445d82ef3a6a2d7e7c0db5e5198287467468962ace5ad063e17e5d6c219f8ed7b6ce6c753297838c04a5934b9fdc0c9fe0b4dca55b8ef12c0",
            "9eda9ea7fa8326cb80aecd6315afe1956b20ee7e60a0b7e58b19fc9ad780acfa8e40a58cf10abcc251ed4a1a226b6e509ea046664a295d3ae4aeffb1",
            "09da30408007de1e2caca06c9163eaf6d441c1d4689a6785e3b6426d1368f7b655b2b9663ba7d4f43977db13362ad4ff008e46c5898d4c57977926f7aa9d548dc62e25707fb2e59525ea415449c02ee296843612c81cbad168f088d35d2ebba1dc0bf90dcdd84bf93a663e3a2170fc81"),
        new TestCase("162626067ca61f0393928af9e6931aefbdda54a1776ead5388a718977a6cc230",
            "37c2d5a0230a1e94cec73542d0a07ff9a199f3f67f2c86e0",
            "4625513a4059074c037a48d6c033443523b072ec162900bbce9d139a33f2d33342",
            "1a02044fb636daf5925469",
            "1d3d0f5c760c6ea07282013f853c2db538ce564b771ee694308533270e32dc88b31472eef1fea4317156766560ccb5cda6"),
        new TestCase("07762246957741daf0486afeeb01746d2706a572157f792738de03b127a02016",
            "a5af745018ea8f266001d22e1b2d06f428f5b82c47b853e3",
            "ee19ed61b1f835aa29df1ee3f1bf6a3bfc62b6580f8b7f3a1297f9b749175035f7abfe8a",
            "3e8f81dee69f3c7b9d313a7f151fdc59c4fee24ccba406505c3afd3e804058dfe89df90bec4fcda8c091f0df2b5def6ee865e84d232e66",
            "3bbc711e971bf20b104ced62afa5bd65904b49d88f058c6e2724eea7c2816b7e939638861386187e4b07491ed869e32878a25b80"),
        new TestCase("23e7c19d5ba541b146b1403f4c1ea990e3aae837f560d912fed87f36e86bc91b",
            "37e5c442f179962d5635701e2b7e2119def2d1ba334f091d",
            "701c8d39922b41f324c7234fd14722622d22a0333a68fd53e6d12cf5136081d93076cf38",
            "bb8540c33d6297c538a68191571ff01189c65aa023c0c01628c6f0514eb541c0b3ffa387e0ca0f6949f67b15ead3ffff13988a668e06",
            "8aa7637d0c67331f4827c68e2761df01897338d9230e1c810f4c8a58fc2feaa2f8e3fa1d7fe4c70c90835a337425392d8ef4b1f0"),
        new TestCase("80c64b636fcf5ebb749a3654617091c75b924c8f4efbce749f9ba92c8e0f4967",
            "61dd9bab5da491d3897cd19724db3f10ed5d7104e91651d4", "7831f7f9e11453495b2dd4856558f8",
            "1e6224186bc830efd07026de94f13a3548668a381da5",
            "a9df1f44741b1748bbfa5024dc2383c2eee3a1f2a10ab504f8959c5c618c63"),
        new TestCase("1982a592e961177e030c91fcbabf24439781bd09f8a8f73916623934abcfe68f",
            "5121b03c73d6f72ca0e41bd1e3d8bfb99299ca9da661a037",
            "38ecaf8b2e5969a2ff9e2818c958b57f0f5b48bf23683d75a0db4a4629d3e50a401acb6888d847c4af7bf4aac5ccd62322f89efb8640358c231e60be70fb03eedaf2a50212f73018e8ab7c272ceade6ab680e3c6d5d5fd6a",
            "647e6df6bd6c8f0b1dbd8ccdf6d111b6717fe7e326b8828722c9ee60f68cd82c3cdab55e",
            "07efc05ecf39ba05a90e79516835f616f8652c5c97be57ab0dde00e7fc09a61b147022e52bd7edf5c449d1c4c660a64567d6bf60a16b8c2bbc0903a12f123e0f1413f1639ac263af9a131564c2002556f2a80789a0938ab29bd425205531eb91e97331684bdbd4fb"),
        new TestCase("3366f519d59a1026f093ee3d86a383122788c0df802683d14f40ae023675fee7",
            "89550e2dd20279a757e7404c1066be40b911ff93e847a9ac",
            "8190be50d139e6bcc360915fe4cc55d85041932b2c0aad6289a777fc4078570b593eb9ed62f7446e7de42e7288ee14",
            "7527503480d49cd130e1eb4a3347117b34f8861bc783f2da8d1b4aa5a38fa1610b33d159dc4a32d267b04ff2ed63706b2a49fc49",
            "bc6a4997059558f5ccc4da172511d89f2eb7d926cf8877db8321a5fd895d11a4703c3c99fce5b51ff3474a741a9b95c01c49d77dd8e888899a9da4baab7821"),
        new TestCase("1f35251df0afa90cfdb4d3257c044bf9300b33522a8aeedcdd0d8503d9934792",
            "27776c7292ecb70ccf0a762be7b8c4955507179263266c57",
            "571784fa3349d596df520a18eddae351c24b37f1fe2a87a58d0a43734ee327decf4c9e65bfbf959fc67d9145d4160c2d42c34eeb58b438321ada2082fec9be0d71949182f8f4bcf0d75eba4d6ee096",
            "37bc72a94b2744e276e21c38024618887c2109f3878ca44581d7623ce08bbc89081a0811",
            "c639ba4e5e4b9a7449fa8e36589b17bcb265d544d9a151272fb090fa66b0263295c5838ad7cc440cb7bed2f2e1934a6d39e0cc95dc9f7b73531174ed8e317348ca216bd4460b69782e5c02ff842317877226b96007a05a44fcfe4bd509222b"),
        new TestCase("0f23ad99e9187b63de26370115cdd1aa45e2302b142e6fbbfe60e7983450387b",
            "da7eec62fda818af0ee5f88e34266be4eab19e47e9e74d90", "790a",
            "94c21e447eb200d3595458280c78feaa1cd4df34bba81cb3a8e143a547c1a7b5",
            "ed916bc45038c18e5f25419f80da4c8d26fe"),
    };

    public String getName()
    {
        return "XChaCha20Poly1305";
    }

    public void performTest() throws Exception
    {
        for (int i = 0; i < TEST_CASES.length; i++)
        {
            performTest(i, TEST_CASES[i]);
        }
    }

    private void performTest(int number, TestCase testCase) throws Exception
    {
        final byte[] plaintext = testCase.getPlaintext();

        XChaCha20Poly1305 engine = new XChaCha20Poly1305();

        if (testCase.aad.length > 0)
        {
            engine.init(true,
                new AEADParameters(new KeyParameter(testCase.getKey()), 128, testCase.getIv(),
                    testCase.getAad()));
        }
        else
        {
            engine.init(true,
                new ParametersWithIV(new KeyParameter(testCase.getKey()), testCase.getIv()));
        }

        byte[] output = new byte[engine.getOutputSize(plaintext.length)];
        int outputBytes = engine.processBytes(testCase.getPlaintext(), 0,
            testCase.getPlaintext().length, output, 0);
        engine.doFinal(output, outputBytes);

        if (!Arrays.areEqual(testCase.getTaggedCiphertext(), output))
        {
            fail("mismatch on " + number, new String(Hex.encode(testCase.getTaggedCiphertext())),
                new String(Hex.encode(output)));
        }
    }

    public static void main(String[] args)
    {
        runTest(new XChaCha20Poly1305Test());
    }
}
