package org.bouncycastle.jcajce.provider.symmetric.hkdf;

import org.bouncycastle.crypto.Digest;
import org.bouncycastle.crypto.digests.SHA256Digest;
import org.bouncycastle.crypto.digests.SHA384Digest;
import org.bouncycastle.crypto.digests.SHA512Digest;
import org.bouncycastle.crypto.generators.HKDFBytesGenerator;
import org.bouncycastle.crypto.params.HKDFParameters;

import javax.crypto.KDFParameters;
import javax.crypto.KDFSpi;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import java.security.InvalidAlgorithmParameterException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.AlgorithmParameterSpec;

class HKDFSpi
        extends KDFSpi
{
    protected HKDFBytesGenerator hkdf;
    public HKDFSpi(KDFParameters kdfParameters)
            throws InvalidAlgorithmParameterException
    {
        super(kdfParameters);
    }

    public HKDFSpi(KDFParameters kdfParameters, Digest digest)
            throws InvalidAlgorithmParameterException
    {
        super(kdfParameters);
        this.hkdf = new HKDFBytesGenerator(digest);
    }

    /**
     * Returns the {@code KDFParameters} used with this {@code KDF} object.
     * <p>
     * The returned parameters may be the same that were used to initialize
     * this {@code KDF} object, or may contain additional default or
     * random parameter values used by the underlying KDF algorithm.
     * If the required parameters were not supplied and can be generated by
     * the {@code KDF} object, the generated parameters are returned;
     * otherwise {@code null} is returned.
     *
     * @return the parameters used with this {@code KDF} object, or
     * {@code null}
     */
    @Override
    protected KDFParameters engineGetParameters()
    {
        return null;
    }

    @Override
    protected SecretKey engineDeriveKey(String alg, AlgorithmParameterSpec derivationSpec)
            throws InvalidAlgorithmParameterException, NoSuchAlgorithmException
    {
        byte[] derivedKey = engineDeriveData(derivationSpec);

        return new SecretKeySpec(derivedKey, alg);
    }
    @Override
    protected byte[] engineDeriveData(AlgorithmParameterSpec derivationSpec)
            throws InvalidAlgorithmParameterException
    {
        if (derivationSpec == null || !(derivationSpec instanceof HKDFParameters))
        {
            throw new InvalidAlgorithmParameterException("Invalid AlgorithmParameterSpec provided");
        }

        HKDFParameters hkdfParameters = (HKDFParameters) derivationSpec;
        int derivedDataLength = hkdfParameters.getIKM().length;

        hkdf.init(hkdfParameters);

        byte[] derivedData = new byte[derivedDataLength];
        hkdf.generateBytes(derivedData, 0, derivedDataLength);

        return derivedData;
    }

    public static class HKDFwithSHA256 extends HKDFSpi
    {
        public HKDFwithSHA256() throws InvalidAlgorithmParameterException
        {
            super(null, new SHA256Digest());
        }
        public HKDFwithSHA256(KDFParameters kdfParameters) throws InvalidAlgorithmParameterException
        {
            super(kdfParameters, new SHA256Digest());
        }
    }
    public static class HKDFwithSHA384 extends HKDFSpi
    {
        public HKDFwithSHA384() throws InvalidAlgorithmParameterException
        {
            super(null, new SHA384Digest());
        }
        public HKDFwithSHA384(KDFParameters kdfParameters) throws InvalidAlgorithmParameterException
        {
            super(kdfParameters, new SHA384Digest());
        }
    }
    public static class HKDFwithSHA512 extends HKDFSpi
    {

        public HKDFwithSHA512() throws InvalidAlgorithmParameterException
        {
            super(null, new SHA512Digest());
        }
        public HKDFwithSHA512(KDFParameters kdfParameters) throws InvalidAlgorithmParameterException
        {
            super(kdfParameters, new SHA512Digest());
        }
    }

}
