package org.bouncycastle.pqc.crypto.ntru;

/**
 * Key pair generated by OWCPA.
 */
class OWCPAKeyPair
{
    public final byte[] publicKey;
    public final byte[] privateKey;

    public OWCPAKeyPair(byte[] publicKey, byte[] privateKey)
    {
        this.publicKey = publicKey;
        this.privateKey = privateKey;
    }
}
